= Vista de Requerimientos: Requerimientos de crypto-kitties

Los requerimientos a implementar en crypto-kitties son:

. Como usuario del sistema,
quiero comprar gatos,
para coleccionarlos.

. Como usuario del sistema,
quiero vender mis gatos,
para ganar dinero.

. Como usuario del sistema,
quiero alquilar mis gatos,
para aparearlos con gatos de otros usuarios.

. Como usuario del sistema,
quiero alquilar gatos de otros usuarios,
para que aparearlos con mis gatos.

. Como usuario del sistema,
quiero ver el catalogo de mis gatos,
para poder ver las características de cada uno de ellos.

. Como usuario del sistema,
quiero cada uno de mis gatos tenga un ADN único,
para que mi gato sea único.

. Como usuario del sistema,
quiero conocer los padres los padres de mi gato,
para saber su pedidrí.

. Como usuario del sistema,
quiero que mi gato tenga las siguientes características: ID único,
edad,
coldown y generación,
para poder determinar su precio.

. Como usuario del sistema,
quiero la opción de dar likes a cualquier gato del juego,
para mostrar mi admiración y gusto por el gato.

. Como usuario del sistema,
quiero listar los gatos del juego con los siguientes filtros: edad,
coldown,
generación y precio,
para poder comprarlos u alquilarlos.

. Como usuario del sistema,
quiero buscar un gato por su ID,
para poder comprarlos u alquilarlos.

. Como sistema,
quiero que cada gato pierda coldown cada vez que se aparee,
para poder controlar la reproducción de los gatos.

. Como internauta,
quiero registrarme en el sistema,
para poder ser parte de este juego. 

. Como usuario,
quiero ingresar al sistema con credenciales únicas,
para acceder al sistema y éste me muestre mi bandeja de gatos. 

. Como sistema,
quiero mostrar una representación gráfica de los gatos basado en su ADN,
para que el usuario puedan ver las características de su gato de forma gráfica.


= Atributos de calidad

Para poder identificar los atributos de calidad se utilizó el framework https://www.neverletdown.net/p/mini-quality-attribute-workshop.html[mini-QAW].


[vega,"spider chart", svg]
----
include::../charts/spider_chart.vega[]
----

Para ello listamos el resultado de dicho trabajo.

== Eficiencia
* Escenarios
. Los usuarios de la aplicación inician una transacción (Compra, venta, etc),
en un entorno de operación normal, el sistema procesa la transacción y muestra el resultado, los datos deben de ser replicados a todos los nodos en máximo 15 minutos
+
[options="",cols="1h,2"]
|===
|Origen|Usuarios del sistema
|Estimulo|Inicio de una transacción (Compra, venta, etc)
|artefacto|Sistema.
|Entorno del sistema|operación normal.
|Respuesta|La transacción es procesada y mostrada al usuario.
|Medición de la respuesta|La data debe de ser guardada y replicada a todos los nodos en máximo 15 minutos.
|===

== Seguridad

* Escenarios
. Un usuario no autenticado inicia de una transacción (Compra, venta, etc), en un entorno de ejecución normal, el sistema rechaza la operación, la identidad del usuario se debe de verificar en menos de 1 segundo.
+
[options="",cols="1h,2"]
|===
|Origen|usuario no autenticado
|Estimulo|Inicio de una transacción (Compra, venta, etc)
|artefacto|Identity verifier.
|Entorno del sistema|operación normal.
|Respuesta|el sistema no le permite realizar la operación.
|Medición de la respuesta|La identidad del usuario debe de ser validad en máximo 1 segundo.
|===
. Un usuario autenticado intenta modificar una característica de su gato, en un entorno de ejecución normal, el distributed legder rechaza la operación, ningún se puede modificar en el legder.  
+
[options="",cols="1h,2"]
|===
|Origen|usuario autenticado
|Estimulo|Usuario desea modificar las características de su item (gato, mascota)
|artefacto|distributed ledger.
|Entorno del sistema|operación normal.
|Respuesta|Transacción rechazada.
|Medición de la respuesta|Ningún registro puede ser modificado.
|===

== Disponibilidad
* Escenarios
. Cuando el monitor de nodos verifica que la cantidad de nodos de tipo FULL disminuye a menos de 10, el automated node deployer crea los nodos para garantizar la cantidad de nodos full disponibles, cada nodo debe de crearse en menos de 2 segundos.
+
[options="",cols="1h,2"]
|===
|Origen|Monitor de nodos
|Estimulo|La cantidad de nodos full disminuya a menos de 10
|artefacto|Automated Node deployer.
|Entorno del sistema|operación normal.
|Respuesta|Se crean nodos full hasta completar la cantidad mínima.
|Medición de la respuesta|cada nodo FULL se debe de crear en menos de 2 segundos.
|===

== Interoperabilidad​ 
* Escenarios
. Los usuarios de la aplicación inician una transacción (Compra, venta, etc),
en un entorno de operación normal, se almacena toda la información de la transacción, los datos deben de ser replicados a todos los nodos en máximo 15 minutos 
+
[options="",cols="1h,2"]
|===
|Origen|Usuario de sistema
|Estimulo|Se registra una nueva transacción
|artefacto|distributed ledger.
|Entorno del sistema|operación normal.
|Respuesta|Se guardará toda la información de la transacción(full data store)
|Medición de la respuesta|La data debe de ser guardada y replicada a todos los nodos en máximo 15 minutos.
|===